name: Run Scripts at Specific Times

on:
  schedule:
    # Hora de Lima, Perú (UTC-5)
    - cron: '0 13 * * *'  # 8:00 AM UTC
  workflow_dispatch:  # Permitir ejecución manual

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        script: [a23.py, a27.py, a31.py, a37.py, a45.py, a53.py, a57.py, a58.py, a60.py, a61.py, a62.py, a64.py, a65.py, a69.py, a70.py, a71.py, a72.py, a73.py, a74.py]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas dropbox openpyxl

    - name: Run the script
      run: python3 ${{ matrix.script }}
      continue-on-error: true
